name: Build and Push Docker image to Dockerhub and AWS EKS for deployment

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
   
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push the Docker image
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: yashgangwar123/wisecow:latest

      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v1
      #   with:
      #     version: 'v1.18.0'

      # - name: Update AWS EKS deployment
      #   run: |
      #     aws eks --region us-east-1 update-kubeconfig --name wisecow
      #     kubectl set image deployment/deployment-wisecow wisecow=yashgangwar123/wisecow:latest -n wisecow
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_DEFAULT_REGION: us-east-1
